name: Deploy Telegram Bot

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ trigger-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd musicBot
            git pull origin master
    
            docker compose down --volumes=false
            docker compose up --build -d